#!/bin/bash
# Add ticket number Of Backlog DEV Team from branch
# if message has no ticket numbers.

if [ -n "${GIT_DIR}" ]; then
  hooksdir="./${GIT_DIR}/hooks/"
else
  hooksdir="./"
fi

. "${hooksdir}common.sh"

appendTicketNumberToCommitMessage $1
