#!/bin/sh
# Add ticket number of Backlog DEV TEAM from branch.

if [ -n "${GIT_DIR}" ]; then
  hooksdir="./${GIT_DIR}/hooks/"
else
  hooksdir="./"
fi

. "${hooksdir}common.sh"

appendTicketNumberToCommitMessage $1
