#!/bin/bash
# Add ticket number of Backlog DEV TEAM from branch.

ticket=`git branch | grep "*" | awk '{print $2}' | sed -e "s/^\(DEV\-[0-9]\+\).*/\1/g"`
if expr $ticket : "^DEV\-[0-9]\+" ; then
    mv $1 $1.tmp
    echo -n "$ticket " > $1
    cat $1.tmp >> $1
    rm $1.tmp
fi

